### ISSUE TITLE
[Error] PubmedCurator was not working because of the lack of altmetric score.

### ISSUE THREAD

**Issue by Imamachi-n** [Imamachi-n/BioRxivCurator#1]
PubmedCurator was not working because of the lack of altmetric score.
Altmetric.com API could not return pct key. 
```
Traceback (most recent call last):
  File "./main4Pubmed.py", line 70, in <module>
    main()
  File "./main4Pubmed.py", line 41, in main
    altmetrics_data = check_altmetrics(doi_info)
  File "/home/pi/Desktop/BioRxivCurator/src/checkAltmetrics.py", line 19, in check_altmetrics
    if response["context"]['journal']['pct'] >= 90:
KeyError: 'context'
```

**Comment by Imamachi-n** [comment]
Skip the articles without altmetric score to escape the above errors. But this fix cannot completely correct  the problem...
